title: Happy Coding
description: I'm Sam, a software developer in Portland Oregon.
show_downloads: true

baseurl: "" 
google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Sam Russell"
image: /thumbnail-jumbo.png
twitter:
  username: samwrussell
github:
  owner_url: "https://github.com/Robooto"
  owner_name: "Sam Russell"
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:
